steps:
- name: node:16.0.0
  entrypoint: npm
  args: ["install"]
- name: node:16.0.0
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'baseURL=${_BASE_URL}'
    - 'spotilizeClientId=${_CLIENT_ID}'
    - 'spotilizeClientSecret=${_CLIENT_SECRET}'
    - 'cloudPlayerCliendId=${_CLOUD_PLAYER_CLIENT_ID}'
    - 'cloudPlayerClientSecret=${_CLOUD_PLAYER_CLIENT_SECRET}'
    - 'cloudPlayerBaseURL=${_CLOUD_PLAYER_BASE_URL}'
    - 'cloudPlayerRedirectURL=${_CLOUD_PLAYER_REDIRECT_URL}'
- name: node:16.0.0
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"